### ISSUE TITLE
P1: adservice-v2 does not  serve GRPC call

### ISSUE THREAD

**Issue by panpan0000** [openinsight-proj/openinsight-helm-charts#108]
From the webstore web UI, no ad shown.

adservice-v2对frontend过来的grpc请求实现可能有遗漏

grpcurl报错：
```
grpcurl -plaintext -d '{"context_keys": ["binoculars","telescopes"]}' 10.233.74.96:8080 oteldemo.AdService/GetAds

Error invoking method "oteldemo.AdService/GetAds": rpc error: code = Unavailable desc = failed to query for service descriptor "oteldemo.AdService": upstream connect error or disconnect/reset before headers. reset reason: protocol error

```

adservice日志
```
2023-04-25 05:42:56.032 trace_id= span_id= trace_flags=  INFO 7 --- [-worker-ELG-3-6] i.g.n.s.i.g.n.N.connections              : Transport failed

io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2Exception: Unexpected HTTP/1.x request: POST /oteldemo.AdService/GetAds
	at io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2Exception.connectionError(Http2Exception.java:108) ~[grpc-netty-shaded-1.42.2.jar!/:1.42.2]
	at io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.readClientPrefaceString(Http2ConnectionHandler.java:302) ~[grpc-netty-shaded-1.42.2.jar!/:1.42.2]
	at io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.decode(Http2ConnectionHandler.java:239) ~[grpc-netty-shaded-1.42.2.jar!/:1.42.2]
	at io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:438) ~[grpc-netty-shaded-1.42.2.jar!/:1.42.2]
	at io.grpc.netty.shaded.io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:508) ~[grpc-netty-shaded-1.42.2.jar!/:1.42.2]
	at io.grpc.netty.shaded.io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:447) ~[grpc-netty-shaded-1.42.2.jar!/:1.42.2]
	at io.grpc.netty.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[grpc-netty-shaded-1.42.2.jar!/:1.42.2]
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[grpc-netty-shaded-1.42.2.jar!/:1.42.2]
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[grpc-netty-shaded-1.42.2.jar!/:1.42.2]
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[grpc-netty-shaded-1.42.2.jar!/:1.42.2]
	at io.grpc.netty.shaded.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[grpc-netty-shaded-1.42.2.jar!/:1.42.2]
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[grpc-netty-shaded-1.42.2.jar!/:1.42.2]
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[grpc-netty-shaded-1.42.2.jar!/:1.42.2]
	at io.grpc.netty.shaded.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[grpc-netty-shaded-1.42.2.jar!/:1.42.2]
	at io.grpc.netty.shaded.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[grpc-netty-shaded-1.42.2.jar!/:1.42.2]
	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) ~[grpc-netty-shaded-1.42.2.jar!/:1.42.2]
	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) ~[grpc-netty-shaded-1.42.2.jar!/:1.42.2]
	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) ~[grpc-netty-shaded-1.42.2.jar!/:1.42.2]
	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) ~[grpc-netty-shaded-1.42.2.jar!/:1.42.2]
	at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[grpc-netty-shaded-1.42.2.jar!/:1.42.2]
	at io.grpc.netty.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[grpc-netty-shaded-1.42.2.jar!/:1.42.2]
	at io.grpc.netty.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[grpc-netty-shaded-1.42.2.jar!/:1.42.2]
	at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]

```

frontend报错

```
Error: 14 UNAVAILABLE: upstream connect error or disconnect/reset before headers. reset reason: protocol error
    at Object.callErrorFromStatus (/app/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
    at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client.js:189:52)
    at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:365:141)
    at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:328:181)
    at /app/node_modules/@grpc/grpc-js/build/src/call-stream.js:187:78
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
  code: 14,
  details: 'upstream connect error or disconnect/reset before headers. reset reason: protocol error',
  metadata: Metadata {
    internalRepr: Map(5) {
      'content-type' => [Array],
      'date' => [Array],
      'server' => [Array],
      'content-length' => [Array],
      'x-envoy-upstream-service-time' => [Array]
    },
    options: {}
  }
}
```

**Comment by Frapschen** [comment]
> reset reason: protocol error

not releate the adservice error
